import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Home from "./page";
export const metadata: Metadata = {
  title: "BEAT+",
  description: "Generated by create next app",
};
// Rename for clarity
// export default function LocaleLayout({
//   children,
//   params: { locale },
// }: Readonly<{
//   children: React.ReactNode;
//   params: { locale: string };
// }>) {
//   return (
//     <html lang={locale}>
//       <body className="...">
//         {/* <NextIntlClientProvider> */}
//         <Home />
//         {children}
//         {/* </NextIntlClientProvider> */}
//       </body>
//     </html>
//   );
// }
export default async function RootLayout({
  //   children,
  // }: Readonly<{
  //   children: React.ReactNode;
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // const messages = await getMessages();
  return (
    <html lang={locale}>
      {/* <html> */}
      <body>
        <NextIntlClientProvider locale={locale}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
